#!/usr/sbin/nft -f

flush ruleset

table inet filter {
	chain INPUT {
		type filter hook input priority filter; policy drop;

		ct state established,related accept comment "Allow traffic originated from us"
		ct state invalid drop comment "Drop invalid connections"

		iif lo accept comment "Accept traffic from localhost"

		tcp dport 22 accept comment "Accept SSH"
		tcp dport 8083 accept comment "Accept connections to adguard home UI"
		udp dport 53 accept comment "Allow udp dns"
		tcp dport 53 accept comment "Allow tcp dns"

		iifname "eth0" udp dport 51820 accept comment "Accept WG connections"
	}
	chain FORWARD {
		type filter hook forward priority filter; policy drop;
		iifname "eth0" oifname "wg0" accept comment "Allow VPN clients to connect (reach wg0 basically)"
		iifname "wg0" oifname "eth0" accept comment "Allow VPN clients to visit the Internet"

		iifname "wg0" oifname "protonvpn" accept comment "Phone traffic to ProtonVPN"
		iifname "protonvpn" oifname "wg0" accept comment "ProtonVPN return traffic to phone"
	}
	chain OUTPUT {
		type filter hook output priority filter; policy accept;
	}
}
table inet wireguard {
	chain PREROUTING {
		type nat hook prerouting priority dstnat; policy accept;
		
		iifname "wg0" ip daddr != 10.154.100.1 udp dport 53 log prefix "DNS-HIJACK: " counter dnat to 10.154.100.1:53
		iifname "wg0" ip daddr != 10.154.100.1 tcp dport 53 log prefix "DNS-HIJACK: " counter dnat to 10.154.100.1:53
	}
	chain POSTROUTING {
		type nat hook postrouting priority srcnat; policy accept;
		oifname "eth0" ip saddr 10.154.100.0/24 masquerade

		oifname "protonvpn" ip saddr 10.154.100.0/24 masquerade comment "Masquerade phone traffic via ProtonVPN"
	}
}

